var arrLang = {
    "zh-ch": {
      "top":" Rushia按钮",
      "title": "欢迎来到Rushia吸毒网",
      "content": "觉得人生好难吗?工作下班回家好没动力吗?想要来点死灵法师吗?点下去吧！按下这些按钮并且大口大口的吸吧！",
      "聲音控制選項":"声音控制选项",
      "stop":"暂停",
      "可愛可愛愛":"可爱可爱爱",
      "叫啊!":"叫啊!",
      "名言佳句":"名言佳句",
      "粽子唱歌":"粽子唱歌",
      "自我介紹": "自我介紹",
      "波音波音波音":"波音波音波音",
      "nanodesu":"nanodesu",
      "阿呀呀":"阿呀呀",
      "大哥哥大姊姊":"大哥哥大姊姊",
      "我回來了":"我回来了",
      "喵":"喵",
      "我愛你":"我爱你",
      "大騙子":"大骗子",
      "RushiRushi":"RushiRushi",
      "JOJOJOJO":"JOJOJOJO",
      "神啊!":"神啊!",
      "RRRRRRRR":"RRRRRRRR",
      "RRRRRRRR2":"RRRRRRRR.2",
      "@$%^#%^@@":"@$%^#%^@@",
      "開甚麼玩笑!!!!(耳膜注意)":"开什么玩笑!!!!(耳膜注意)",
      "為什麼騙我 吶!":"为什么骗我 呐!",
      "你是誰?":"你是谁?",
      "約定好了啊":"约定好了啊",
      "認清現實吧":"认清现实吧",
      "看啊!看啊!":"看啊!看啊!",
      "你給我記住":"你给我记住",
      "永不放棄":"永不放弃",
      "起床鬧鐘":"起床闹钟",
      "別認輸":"别认输",
      "ending":"关台动画",
      "opening":"开台动画", 
      "renew":"2020.7.2 考量到空间问题设置连结集中更新" ,
      "renew0":"更新日志",
      "touchme":"点我点我",
      "author":"作者:YiYu, 特别感谢:google大神、岛辉叔叔",
      "stateman":"本站为爱好者作品，与hololive官方没有任何关系，如有任何问题或建议欢迎discord找我 → 拒絕往來戶#6977",
      "painter":"背景图画师:KayJae",
      "marquee":"2020.7.30因应Hololive今次的版权问题将暂时停更音档，现有的不会删除还请安心食用",
    
    },
    "zh-tw": {
      "top":"Rushia按鈕",
      "title": "歡迎來到Rushia吸毒網",
      "content": "覺得人生好難嗎?工作下班回家好沒動力嗎?想要來點死靈法師嗎?點下去吧！按下這些按鈕並且大口大口的吸吧！",
      "聲音控制選項":"聲音控制選項",
      "stop":"暫停",
      "可愛可愛愛":"可愛可愛愛",
      "叫啊!":"叫啊!",
      "名言佳句":"名言佳句",
      "粽子唱歌":"粽子唱歌",
      "自我介紹": "自我介紹",
      "波音波音波音":"波音波音波音",
      "nanodesu":"nanodesu",
      "阿呀呀":"阿呀呀",
      "大哥哥大姊姊":"大哥哥大姊姊",
      "我回來了":"我回來了",
      "喵":"喵",
      "我愛你":"我愛你",
      "大騙子":"大騙子",
      "RushiRushi":"RushiRushi",
      "JOJOJOJO":"JOJOJOJO",
      "神啊!":"神啊!",
      "RRRRRRRR":"RRRRRRRR",
      "RRRRRRRR2":"RRRRRRRR.2",
      "@$%^#%^@@":"@$%^#%^@@",
      "開甚麼玩笑!!!!(耳膜注意)":"開甚麼玩笑!!!!(耳膜注意)",
      "為什麼騙我 吶!":"為什麼騙我 吶!",
      "你是誰?":"你是誰?",
      "約定好了啊":"約定好了啊",
      "認清現實吧":"認清現實吧",
      "看啊!看啊!":"看啊!看啊!",
      "你給我記住":"你給我記住",
      "永不放棄":"永不放棄",
      "起床鬧鐘":"起床鬧鐘",
      "別認輸":"別認輸",
      "ending":"關台動畫",
      "opening":"開台動畫",
      "renew":"2020.7.2 考量到空間問題設置連結集中更新",
      "renew0":"更新日誌",
      "touchme":"點我點我",
      "author":"作者:YiYu, 特別感謝:google大神、島輝叔叔",
      "stateman":"本站為愛好者作品，與hololive官方沒有任何關係，如有任何問題或建議歡迎discord找我 → 拒絕往來戶#6977",
      "painter":"背景圖畫師:KayJae",
      "marquee":"2020.7.30 因應Hololive今次的版權問題將暫時停更音檔，現有的不會刪除還請安心食用",    
    
    },
    "en-gb":{
      "top":"Rushia_btn",
      "title": "Welcome to Rushia Drug Network",
      "content": "Do you think life is so difficult? Is it so unmotivated to go home from get off work? Do you want some necromancer? Click it! Press these buttons and suck it!",
      "聲音控制選項":"Sound control options",
      "stop":"Stop",
      "可愛可愛愛":"Cute",
      "叫啊!":"Roar!",
      "名言佳句":"Inspirational quotes",
      "粽子唱歌":"Zongzi singing",
      "自我介紹": "Self introduction",
      "波音波音波音":"BoingBoingBoing",
      "nanodesu":"nanodesu",
      "阿呀呀":"Ayah",
      "大哥哥大姊姊":"Brother and sister",
      "我回來了":"I am back",
      "喵":"Meow~",
      "我愛你":"I love you",
      "大騙子":"Cheater",
      "RushiRushi":"RushiRushi",
      "JOJOJOJO":"JOJOJOJO",
      "神啊":"God!",
      "RRRRRRRR":"RRRRRRRR",
      "RRRRRRRR2":"RRRRRRRR.2",
      "@$%^#%^@@":"@$%^#%^@@",
      "開甚麼玩笑!!!!(耳膜注意)":"What a joke!!!!(Eardrum attention)",
      "為什麼騙我 吶!":"Why lie to me na!",
      "你是誰?":"Who are you?",
      "約定好了啊":"It's agreed",
      "認清現實吧":"Recognize reality",
      "看啊!看啊!":"Look! Look!",
      "你給我記住":"Just you remember",
      "永不放棄":"Never give up",
      "起床鬧鐘":"Wake up alarm clock",
      "別認輸":"Don't give up",
      "ending":"Ending animation",
      "opening":"Opening animation",
      "renew":"2020.7.2 Considering spatial issues, setting links are centrally updated",
      "renew0":"Upadta log",
      "touchme":"Touch me",
      "author":"Author: YiYu, Special thanks: google, Tank島輝",
      "stateman":"This site is for fans, and has nothing to do with hololive. If you have any questions or suggestions, please discord me → 拒絕往來戶#6977",
      "painter":"Background image Artist: KayJae",
      "marquee":"2020.7.30 In response to Hololive’s copyright issues this time, we will temporarily stop updating audio files. The existing ones will not be deleted. Please feel free to eat",

    },
    // "jp":{
    //   "title": "",
    //   "content": "",
    //   "聲音控制選項":"",
    //   "stop":"",
    //   "可愛可愛愛":"",
    //   "叫啊!":"",
    //   "名言佳句":"",
    //   "粽子唱歌":"",
    //   "自我介紹": "",
    //   "波音波音波音":"",
    //   "nanodesu":"",
    //   "阿呀呀":"",
    //   "大哥哥大姊姊":"",
    //   "我回來了":"",
    //   "喵":"",
    //   "我愛你":"",
    //   "大騙子":"",
    //   "RushiRushi":"",
    //   "JOJOJOJO":"",
    //   "神啊!":"",
    //   "RRRRRRRR":"",
    //   "RRRRRRRR2":"",
    //   "@$%^#%^@@":"@$%^#%^@@",
    //   "開甚麼玩笑!!!!(耳膜注意)":"",
    //   "為什麼騙我 吶!":"",
    //   "你是誰?":"",
    //   "約定好了啊":"",
    //   "認清現實吧":"",
    //   "看啊!看啊!":"",
    //   "你給我記住":"",
    //   "永不放棄":"",
    //   "起床鬧鐘":"",
    //   "別認輸":"",
    // },
  };
  
 $(function(){
     $('.translate').click(function(){
         var lang = $(this).attr('id');

         $('.lang').each(function(index, element){
             $(this).text(arrLang[lang][$(this).attr('key')]);
         });
     });
 })